### ISSUE TITLE
Trouble with Mun example script

### ISSUE THREAD

**Issue by mathuin** [artwhaley/krpcmj#2]
I tried the example script of a flight to the Mun, using the Kerbal X in a sandbox game.

It finished the circularization burn (and that awkwardly) but didn't do anything else.

Here's the output:

``````
(ksp)jmt@nala:~$ python ./to-the-mun.py 
Vessel Ready for launch...
Launching Vessel to 85km Parking Orbit

Awaiting liftoff
Vertical ascent
Gravity turn
Fine tuning apoapsis
Coasting to edge of atmosphere
Coasting to circularization burn
Circularizing
Launch Complete
Apoapsis: 84668.1964825
Periapsis: 83672.0235268
Targeting Moon
Using Rendezvous Autopilot for Plane Change and Transfer Burn...
Mun SOI Achieved.  Adjusting Periapsis...
Traceback (most recent call last):
  File "./to-the-mun.py", line 44, in <module>
    mj.mp_pea(sc.ut,sc.active_vessel.orbit.body.equatorial_radius+15000)  # Set Periapsis to 15km above surface
  File "<string>", line 1, in <lambda>
  File "/home/jmt/.virtualenvs/ksp/local/lib/python2.7/site-packages/krpc/client.py", line 87, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: 'krpcmj.mpPea' threw an exception. System.TypeLoadException: Could not load type 'Vector3d' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0```
``````

**Comment by mathuin** [comment]
Reinstalled KSP with no mods except MJ, KER, and kRPC.

Launched with Kerbal X.

```
(ksp)jmt@nala:~$ python ./to-the-mun.py 
Vessel Ready for launch...
Launching Vessel to 85km Parking Orbit

Awaiting liftoff
Vertical ascent
Gravity turn
Fine tuning apoapsis
Coasting to edge of atmosphere
Coasting to circularization burn
Circularizing
Launch Complete
Apoapsis: 85152.98749
Periapsis: 84799.5392349
Targeting Moon
Using Rendezvous Autopilot for Plane Change and Transfer Burn...
Mun SOI Achieved.  Adjusting Periapsis...
Traceback (most recent call last):
  File "./to-the-mun.py", line 44, in <module>
    mj.mp_pea(sc.ut,sc.active_vessel.orbit.body.equatorial_radius+15000)  # Set Periapsis to 15km above surface
  File "<string>", line 1, in <lambda>
  File "/home/jmt/.virtualenvs/ksp/local/lib/python2.7/site-packages/krpc/client.py", line 87, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: Could not load type 'Vector3d' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

Wondered if it was the rocket at fault here.  This launch was with a PT Series Munsplorer:

```
(ksp)jmt@nala:~$ python ./to-the-mun.py Vessel Ready for launch...
Launching Vessel to 85km Parking Orbit

Vertical ascent
Gravity turn
Fine tuning apoapsis
Coasting to edge of atmosphere
Coasting to circularization burn
Circularizing
Off
Launch Complete
Apoapsis: 85010.2267414
Periapsis: 84707.2494965
Targeting Moon
Using Rendezvous Autopilot for Plane Change and Transfer Burn...
Mun SOI Achieved.  Adjusting Periapsis...
Traceback (most recent call last):
  File "./to-the-mun.py", line 44, in <module>
    mj.mp_pea(sc.ut,sc.active_vessel.orbit.body.equatorial_radius+15000)  # Set Periapsis to 15km above surface
  File "<string>", line 1, in <lambda>
  File "/home/jmt/.virtualenvs/ksp/local/lib/python2.7/site-packages/krpc/client.py", line 87, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: Could not load type 'Vector3d' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

**Comment by mathuin** [comment]
This issue is no longer exhibited.  Circularization after ascent is much improved, and periapsis is set correctly when approaching the Mun.  Landing isn't working, but that's a separate thing.  I'm closing this issue.
