### ISSUE TITLE
krpc.error.RPCError: Method not found: 'PartModuleList.GetEnumerator'.

### ISSUE THREAD

**Issue by jonasrosland** [artwhaley/krpcmj#3]
When I try to use your simple launch example from the wiki with KSP 1.2.2 and kRPC 0.3.7, I get the following error message:

```
$ python3 simplelaunch.py
Traceback (most recent call last):
  File "simplelaunch.py", line 8, in <module>
    mj.ascent_alt=85000                          ##Orbital Altitude:
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.5/site-packages/krpc/client.py", line 88, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: Method not found: 'PartModuleList.GetEnumerator'.
```

Any idea what's wrong?

My `ckan list`:

```
KSP Version: 1.2.2.1622

Installed Modules:

- KerbalEngineerRedux 1.1.2.8
- kRPC v0.3.7
- krpcmj autodetected dll
- KSPSteamCtrlr autodetected dll
- MechJeb2 2.6.0.0
- MechJebForAll 1.2.0.0
- ModuleManager 2.7.5
- Steamworks autodetected dll
```

**Comment by djungelorm** [comment]
Looks like krpcmj needs updating for KSP 1.2.2

**Comment by jonasrosland** [comment]
That would be great!

**Comment by mathuin** [comment]
Out of curiosity, where would one find out what one would need to know to update this project?  

https://wiki.kerbalspaceprogram.com/wiki/1.2.2 and friends seem a little light on the details.  https://kerbalspaceprogram.com/api/class_part_module_list.html shows the existence of an inline  `GetEnumerator()` method in the `PartModuleList` class.  Is this last site out of date?

**Comment by djungelorm** [comment]
It appears to work with KSP 1.3.1, if you use the changes in my pull request (https://github.com/artwhaley/krpcmj/pull/4)

Here's a binary so you don't have to compile it yourself: https://www.dropbox.com/s/ob6hji3e8awdxab/krpcmj.dll?dl=0

**Comment by mathuin** [comment]
The one tweak I had to make to your pull request was with regard to `Partials/Rover.cs` as it was missing.  Other than that, I was able to build the DLL and it "worked" -- crashed my lander on the Mun but all the MJ magic got it there at least!

**Comment by mathuin** [comment]
@artwhaley noticed that #4 was merged, which should fix this issue.  Can this issue be closed as a result?
